Repository ifmeorg/ifme, pull requests merged in 2018-10, with the labels that each got.

#1088 Changed word without much sense in Spanish
  config/locales/es.yml
Labels: translations

#1076 Refactor meetings controller part 1
  app/controllers/meetings_controller.rb
  app/helpers/meetings_helper.rb
  app/models/group.rb
  app/models/meeting.rb
  spec/controllers/meetings_controller_spec.rb
  spec/factories/factories.rb
  spec/models/group_spec.rb
  spec/models/meeting_spec.rb
Labels: enhancement, ready-for-review, ruby on rails

#1087 [Issue #1054] Added spec coverage for group_notifier
  spec/services/group_notifier_spec.rb
Labels: hacktoberfest, ruby on rails, tests

#1080 [WIP] Refactor meetings controller2
  app/controllers/meetings_controller.rb
Labels: wip

#1114 Refactor Omniauth Callbacks Controller
  app/controllers/omniauth_callbacks_controller.rb
  spec/controllers/omniauth_callbacks_controller_spec.rb
  spec/spec_helper.rb
  spec/support/stub_google_oauth2.rb
Labels: refactoring

#1113 Rescue from specific errors
  app/controllers/categories_controller.rb
  app/controllers/medications_controller.rb
  app/controllers/moments_controller.rb
  app/controllers/moods_controller.rb
  app/controllers/strategies_controller.rb
  app/helpers/application_helper.rb
  app/helpers/date_time_helper.rb
  app/helpers/medication_refill_helper.rb
  app/models/user.rb
  spec/factories/factories.rb
  spec/features/user_creates_a_medication_spec.rb
  spec/helpers/medication_refill_helper_spec.rb
  spec/models/user_spec.rb
Labels: refactoring

#1216 Update text in test file to be consistent with naming
  spec/compare_locales_support_spec.rb
Labels: tests
