Repository ifmeorg/ifme, pull requests merged in 2018-12, with the labels that each got.

#1098 [#975] Convert blurbs to use Modal components.
  app/assets/javascripts/contributors_readmore.js
  app/assets/stylesheets/application/contributors.scss
  app/assets/stylesheets/base/_sizes.scss
  app/views/pages/_contributor_blurb.html.erb
  app/views/pages/contribute.html.erb
  client/app/components/Modal/Modal.scss
  client/app/components/Modal/__tests__/Modal.spec.jsx
  client/app/components/Modal/index.jsx
  client/app/stories/Modal.stories.jsx
  client/yarn.lock
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/nb.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/sv.yml
  config/locales/vi.yml
  spec/javascripts/ContributorsReadMoreSpec.js
Labels: wip

#1286 Translations for moods in ja.yml
  config/locales/ja.yml
Labels: translations

#1305 Rewrite compare_locales_support_spec to be dynamic
  config/application.rb
  config/locale.rb
  spec/compare_locales_support_spec.rb
  spec/support/compare_locales_support.rb
Labels: refactoring, tests
