Repository ifmeorg/ifme, pull requests merged in 2018-09, with the labels that each got.

#949 Code of Conduct added in Footer
  app/helpers/notification_mailer_helper.rb
  app/views/shared/_footer.html.erb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/it.yml
  config/locales/nb.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/sv.yml
  config/locales/vi.yml
  config/routes.rb
Labels: RGSoC 2018

#960 Contributor Blurb for Atibhi
  app/assets/images/contributors/atibhi_agrawal.jpg
  doc/pages/blurbs.json
  doc/pages/contributors.json
Labels: RGSoC 2018

#979 Added Hyperlinks to FAQ pages
  app/views/groups/index.html.erb
  app/views/pages/faq.html.erb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/it.yml
  config/locales/nb.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/sv.yml
  config/locales/vi.yml
Labels: RGSoC 2018

#998 Add Codeclimate Test Coverage to CircleCI
  .circleci/config.yml
  README.md
  client/.gitignore
Labels: wip

#1000 #976 HTTP security headers patch
  config/application.rb
Labels: security
