Repository ifmeorg/ifme, pull requests merged in 2020-10, with the labels that each got.

#1852 Move errors controller spec to request spec
  spec/requests/error_handling_spec.rb
Labels: wip

#1867 Refactor/categories spec
  spec/controllers/categories_controller_spec.rb
  spec/requests/categories_spec.rb
Labels: tests

#1875 [Issue #1839] Refactor secret_shares controller spec to request spec
  spec/requests/secret_shares_spec.rb
Labels: refactoring, tests

#1876 Adds myself (Camila Campos) to contributors
  app/assets/images/contributors/camila_campos.png
  doc/pages/blurbs.json
Labels: contributor community

#1886 Refactor care_plan controller tests into request tests
  spec/controllers/care_plan_controller_spec.rb
  spec/requests/care_plan_spec.rb
Labels: wip

#1902 Refactored pusher_controller_spec to pusher_spec
  spec/requests/pusher_spec.rb
Labels: hacktoberfest, refactoring, tests

#1903 Refactor notification controller spec to notification request spec
  spec/requests/notifications_spec.rb
Labels: hacktoberfest

#1922 [Issue #1820] Refactor care plan contacts controller spec to request spec
  spec/controllers/care_plan_contacts_controller_spec.rb
  spec/requests/care_plan_contacts_spec.rb
Labels: refactoring, tests

#1900 Data to csv
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  app/controllers/users/reports_controller.rb
  app/helpers/users/reports_helper.rb
  app/models/allyship.rb
  app/models/application_record.rb
  app/models/care_plan_contact.rb
  app/models/category.rb
  app/models/group.rb
  app/models/group_member.rb
  app/models/medication.rb
  app/models/meeting_member.rb
  app/models/moment.rb
  app/models/mood.rb
  app/models/notification.rb
  app/models/strategy.rb
  app/models/user.rb
  app/models/users.rb
  app/models/users/data_request.rb
  app/workers/delete_stale_data_worker.rb
  app/workers/process_data_request_worker.rb
  config/env/development.example.env
  config/env/test.example.env
  config/initializers/sidekiq.rb
  config/routes.rb
  config/sidekiq.yml
  config/sidekiq_schedule.yml
  db/migrate/20201008170831_create_users_data_requests.rb
  db/schema.rb
  spec/factories/users/data_requests.rb
  spec/models/users/data_request_spec.rb
  spec/requests/users/reports_request_spec.rb
Labels: hacktoberfest, hacktoberfest-accepted
