Repository ifmeorg/ifme, pull requests merged in 2020-05, with the labels that each got.

#1740 Upgrade: Rails 6.0.3
  Gemfile
  Gemfile.lock
  bin/setup
  client/yarn.lock
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults_6_0.rb
  config/puma.rb
  config/spring.rb
  config/storage.yml
  db/migrate/20200509110917_add_foreign_key_constraint_to_active_storage_attachments_for_blob_id.active_storage.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: high priority, ruby, ruby on rails, wip

#1757 Fix: update seeds
  db/seeds.rb
Labels: bug

#1759 Translation Readme.md into Korean
  README-KO.md
Labels: translations
